[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tccdem_api"
version = "0.1.0"
description = "API client for managing and querying the TCCDEM materials database."
authors = [
    { name="Cem Oran", email="oranc@itu.edu.tr"}
]

readme = "README.md"
requires-python = ">=3.9"

dependencies = ["mysql-connector-python"]

[tool.setuptools.packages.find]
where = ["."]
include = ["tccdem_api*"]


# Include non-Python files (like CSVs) inside the installed package directory
[tool.setuptools.package-data]
"tccdem_api" = ["data/*"]